# ============================
# App config
# ============================
spring.application.name=Virtual Clubs

info.app.name=VirtualClubs
info.app.description=Backend for VirtualClubs sports clubs management
info.app.version=0.0.1

spring.profiles.active=dev

server.port=${PORT:8080}
app.deeplink-url=https://virtualclubs-backend.onrender.com

# ============================
# Metrics
# ============================
app.cors.allowed-origins=https://virtualclubs-backend.onrender.com:3000

# ============================
# Database
# ============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://${JDBC_DATABASE_URL:ep-plain-pine-agaanizb-pooler.c-2.eu-central-1.aws.neon.tech}:${JDBC_DATABASE_PORT:5432}/${JDBC_DATABASE_NAME:VirtualClubs Backend Dev}
spring.datasource.username=${JDBC_DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:npg_LB6ThNbJ9wpf}

# ============================
# JWT
# ============================
jwt.secret=${JWT_SECRET:0cr57acm5fbb6496f3c73f2e61y3e2f81afyea9bcaaiffe1cj35e2681667ve44}

jwt.expiration=36000000
jwt.refreshExpiration=604800000

# ============================
# Google Content ID
# ============================
google.id=${GOOGLE_CONTENT_ID:***ELIMINADO***}

# ============================
# Spring Mail config
# ============================
spring.mail.from=virtualclub.spain@gmail.com
app.mail.sendGridApiKey=${SENDGRID_API_KEY:***ELIMINADO***}

app.token.emailVerificationExpiryHours=48
app.token.passwordResetExpiryHours=1