jwt.secret=***ELIMINADO***

spring.datasource.url=jdbc:postgresql://localhost:5432/virtualclub
spring.datasource.username=virtualclub
spring.datasource.password=virtualclub

logging.level.root=INFO
logging.level.galindo.raul.virtualclubs=DEBUG

management.endpoints.web.exposure.include=health,info,metrics,logfile

google.id=879741762461-lf3jj7cl1djmucjb8kn0ikibf4cp9ct3.apps.googleusercontent.com

server.port=8080
server.ssl.key-store=keystore.p12
server.ssl.key-store-password=***ELIMINADO***
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myserver