logging.level.root=INFO
logging.level.galindo.raul.virtualclubs=DEBUG

management.endpoints.web.exposure.include=health,info,metrics,logfile

server.port=${PORT}

# ============================
# Database
# ============================
spring.datasource.url=jdbc:postgresql://postgres:5432/${NAME_DATABASE_POSTGRESS_DEBUG}
spring.datasource.username=${USERNAME_DATABASE_POSTGRESS_DEBUG}
spring.datasource.password=${PASSWORD_DATABASE_POSTGRESS_DEBUG}

# ============================
# JWT
# ============================
jwt.secret=${JWT_SECRET_DEBUG}

# ============================
# Google Content ID
# ============================
#google.id=${GOOGLE_CONTENT_ID}

# ============================
# Spring Mail config
# ============================
spring.mail.from=virtualclub.spain@gmail.com
#app.mail.sendGridApiKey=${SENDGRID_API_KEY:***ELIMINADO***}

app.token.emailVerificationExpiryHours=48
app.token.passwordResetExpiryHours=1