# ============================
# App config
# ============================
spring.application.name=Virtual Clubs

info.app.name=VirtualClubs
info.app.description=Backend for VirtualClubs sports clubs management
info.app.version=0.0.1

spring.profiles.active=dev

server.port=${PORT:8080}
app.deeplink-url=virtualclubs

# ============================
# Metrics
# ============================
app.cors.allowed-origins=https://virtualclubs-backend.onrender.com:3000

# ============================
# Database
# ============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://${JDBC_DATABASE_URL}:${JDBC_PORT_PASSWORD}/${JDBC_DATABASE_NAME}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

# ============================
# JWT
# ============================
jwt.secret=${JWT_SECRET}

jwt.expiration=36000000
jwt.refreshExpiration=604800000

# ============================
# Google Content ID
# ============================
google.id=${GOOGLE_CONTENT_ID}

# ============================
# Spring Mail config
# ============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.token.emailVerificationExpiryHours=48
app.token.passwordResetExpiryHours=1