logging.level.root=INFO
logging.level.galindo.raul.virtualclubs=INFO

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true

google-id=879741762461-lf3jj7cl1djmucjb8kn0ikibf4cp9ct3.apps.googleusercontent.com